name: "Setup Student ID"
description: "Reads and validates student ID"
runs:
  using: "composite"
  steps:
    - name: Kontrollera ID
      shell: bash
      run: |
        # 1. Kontrollera filen
        if [ ! -f student.json ]; then
          echo "::error::Filen student.json saknas!"
          exit 1
        fi

        # 2. Läs och validera ID
        ID=$(jq -r '.student_id' student.json)

        if [ "$ID" == "null" ] || [ "$ID" == "SKRIV_DITT_ID_HÄR" ] || [ -z "$ID" ]; then
           echo "::error::Ogiltigt ID i student.json"
           exit 1
        fi

        # 3. Spara till ENV så alla andra steg ser det
        echo "STUDENT_ID=$ID" >> $GITHUB_ENV
        echo "✅ Student ID: $ID"
