name: "Grading Feedback"
description: "Posts feedback table to PR"
runs:
  using: "composite"
  steps:
    - name: Post Comment
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');

          let body = "";
          const runNumber = context.runNumber;
          const now = new Date().toLocaleString('sv-SE', { 
            timeZone: 'Europe/Stockholm',
            year: 'numeric', month: '2-digit', day: '2-digit',
            hour: '2-digit', minute: '2-digit'
          });

          // 1. KOLLA OM RESULTAT FINNS
          if (fs.existsSync('grading-results.json')) {
            const results = JSON.parse(fs.readFileSync('grading-results.json', 'utf8'));
            const studentId = process.env.STUDENT_ID || "Okänd";

            const totalPoints = results.reduce((sum, r) => sum + r.score, 0);
            const maxPoints = results.reduce((sum, r) => sum + r.points, 0);

            const rows = results.map(r => 
              `| ${r.passed ? '✅' : '❌'} | ${r.name} | ${r.score} / ${r.points} |`
            ).join('\n');

            body = `
            ## 🤖 Automatisk Rättning
            **Student:** ${studentId}
            **Resultat:** ${totalPoints} / ${maxPoints} poäng
            **Försök:** #${runNumber}
            
            | Status | Uppgift | Poäng |
            | :---: | :--- | :---: |
            ${rows}
            
            *(Kördes: ${now})*
            `;

          } else {
            console.log("Ingen resultatsfil hittades. Antar setup-fel.");
            
            body = `
            ## ⚠️ Automatisk Rättning Misslyckades
            **Status:** ❌ Setup misslyckades
            **Försök:** #${runNumber}

            Botten kunde inte köra dina tester. Detta beror oftast på:
            1. **student.json** saknas eller har fel format.
            2. Du har inte fyllt i **student_id** korrekt.
            3. Ett kritiskt fel i koden (syntax error) stoppade starten.

            🔍 **Åtgärd:** Kontrollera fliken "Checks" här på GitHub för att se exakt vad som gick fel.
            
            *(Kördes: ${now})*
            `;
          }

          // --- 2. HITTA PR OCH POSTA ---
          try {
            const prs = await github.rest.pulls.list({ 
              owner: context.repo.owner, 
              repo: context.repo.repo, 
              state: 'open' 
            });

            if (prs.data.length > 0) {
              const prNumber = prs.data[0].number;
              
              const comments = await github.rest.issues.listComments({ 
                owner: context.repo.owner, 
                repo: context.repo.repo, 
                issue_number: prNumber 
              });
              
              const botComment = comments.data.find(c => c.body.includes('## 🤖 Automatisk Rättning') || c.body.includes('## ⚠️ Automatisk Rättning Misslyckades'));

              if (botComment) {
                await github.rest.issues.updateComment({ 
                  owner: context.repo.owner, 
                  repo: context.repo.repo, 
                  comment_id: botComment.id, 
                  body: body 
                });
                console.log("Uppdaterade kommentar.");
              } else {
                await github.rest.issues.createComment({ 
                  owner: context.repo.owner, 
                  repo: context.repo.repo, 
                  issue_number: prNumber, 
                  body: body 
                });
                console.log("Skapade ny kommentar.");
              }
            } else {
              console.log("Ingen öppen PR hittades.");
            }
          } catch (e) {
            console.log("Kunde inte posta kommentar: " + e.message);
          }
